version: '3.8'

services:
  mysql:
    image: 'mysql:8.0'
    container_name: 'java-mysql'
    environment:
      - 'MYSQL_ROOT_USER=root'
      - 'MYSQL_ROOT_PASSWORD=root505'
      - 'MYSQL_DATABASE=kata_task_3.1.4_with_docker'
    restart: always
    networks:
      - my_network

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    restart: always
    networks:
      - my_network

networks:
  my_network: